// Wörterbuch (de/en) — Basis. Weitere Dateien in diesem Ordner werden tief gemischt.
export default {
  de: {
    'titel': 'Icon Pipeline',
    'tab.icon': 'Icon',
    'tab.cfg': 'Einstellungen',
    'tab.bericht': 'Bericht',
    'adapter.zds': 'ZDS',
    'adapter.frei': 'Frei',

    'auswahl.leer': 'Icon auswählen …',
    'auswahl.tip': 'Klick: im Canvas zeigen',
    'btn.vorschau': 'Vorschau',
    'btn.bauen': 'Icon bauen',
    'tip.snap': 'Gerade Kanten und Kurven-Scheitel aufs eingestellte Raster. Das AA-Orakel behält automatisch die schärfere Fassung. Gilt fürs Durchziehen und für „Alle neu bauen“.',
    'chk.snap': 'Pixel-Snapping',
    'tip.stroke': 'Ungeplättete Fassung neben der Vorlage, kantenidentisch zum Ergebnis. Wird nicht publiziert.',
    'chk.stroke': 'Stroke-Fassung ablegen',
    'klasse.erkl': 'Die Klasse bestimmt Keyline und Einpass-Achse. Kreise brauchen eine größere Keyline als Quadrate.',
    'klasse.festTip': 'Die Klasse kommt aus dem Grid des Boards.',
    'klasse.wechselnTip': 'Klicken, um die Klasse zu wechseln.',
    'klasse.geratenTip': 'Aus dem Seitenverhältnis geraten — Kreis oder Quadrat? Klicken zum Festlegen.',

    'umf.icon': 'Dieses Icon',
    'umf.library': 'Ganze Library',
    'btn.audit': 'Prüfen',
    'btn.alle': 'Alle bauen',
    'btn.undo': 'Rückgängig',
    'btn.undoN': 'Rückgängig ({n})',
    'tip.undo': 'Ein Schritt = ein Icon.',
    'btn.abbrechen': 'Abbrechen',

    'dlg.plan.titelAlle': 'Alle Icons neu bauen?',
    'dlg.plan.titelEins': 'Icon bauen?',
    'dlg.plan.textAlle': 'Trockenlauf — noch wurde nichts verändert. Das steht an:',
    'dlg.plan.textEins': 'Trockenlauf — noch wurde nichts verändert.',
    'dlg.plan.leer': 'Nichts zu bauen.',
    'plan.aendern': 'ändern',
    'plan.neu': 'neu',
    'plan.fehlen': 'fehlt: {liste}',
    'plan.fremd': 'fremd: {liste}',
    'plan.instanzen': '{n} Instanzen',
    'plan.instanzenUnbekannt': 'Instanzen ?',
    'plan.gesperrt': 'gesperrt',
    'plan.summe': '{aendern} ändern · {neu} neu · {fehlen} Varianten fehlen · {gesperrt} gesperrt · {instanzen} Instanzen',
    'plan.strokeHeim': 'Ein Frame für Stroke-Fassungen wird angelegt.',
    'btn.planBauen': 'Bauen',
    'chk.trockenlaufEinzel': 'Trockenlauf beim Einzelbau überspringen',

    'leer.karte': 'Wähle eine Karte auf dem ZDS-Board aus.',
    'leer.kurz': 'Wähle eine Vorlage im Canvas — oder wechsle auf „Ganze Library“.',
    'btn.beispiel': 'Beispiel-Icon anlegen',

    'diff.nuralt': 'kein bestehendes Set',
    'zoom.kleiner': 'kleiner',
    'zoom.groesser': 'größer',

    'zelle.keyline': 'Keyline {ist}/{soll}',
    'zelle.gerastet': '{n} Kanten gerastet',

    'log.titel': 'Protokoll',
    'btn.leeren': 'Leeren',
    'log.leer': 'Noch nichts gelaufen.',
    'log.zeigen': 'zeigen',

    'cfg.allgemein': 'Allgemein',
    'cfg.adapter': 'Adapter',
    'cfg.sprache': 'Sprache',
    'cfg.variantenProperty': 'Variantenproperty',
    'opt.auto': 'automatisch',
    'opt.zds': 'ZDS',
    'opt.frei': 'Frei',
    'opt.de': 'Deutsch',
    'opt.en': 'Englisch',

    'cfg.master': 'Master',
    'cfg.masterGroesse': 'Größe',
    'cfg.masterKontur': 'Strichstärke (px)',
    'cfg.keylines': 'Keyline (Icon-Körper)',

    'cfg.groessen': 'Größen',
    'cfg.N': 'N (px)',
    'cfg.kontur': 'Strichstärke (px)',
    'cfg.raster': 'Kanten rasten auf',
    'cfg.rasterGrob': 'Ganze Pixel bevorzugen',
    'cfg.radiusModus': 'Eckenradien',
    'cfg.radiusWert': 'Radius (px)',
    'cfg.radiusMin': 'Mindestradius (px)',
    'cfg.standard': 'Standard',
    'cfg.entfernen': 'Größe entfernen',
    'cfg.keylinesAuf': 'Keyline (Icon-Körper)',
    'cfg.keylinesProp': 'proportional neu berechnen',
    'cfg.keylinesLegende': 'Kasten {N} px · Pixelraster · Formklassen: Square, Circular, Wide, Tall',
    'cfg.keylinesHinweis': 'Die Keyline ist die Größe des Icon-Körpers im {N}-px-Kasten. Sie folgt N automatisch, bis du sie von Hand änderst.',
    'cfg.keylineUnplausibel': 'Keyline {wert} passt nicht zu N = {N} (erwartet zwischen {min} und {N}).',
    'btn.groesseHinzu': 'Größe hinzufügen',
    'opt.aus': 'aus',
    'radius.proportional': 'proportional verkleinern',
    'radius.fest': 'fester Wert',
    'radius.keine': 'keine Rundung',

    'cfg.farbe': 'Farbe',
    'farbe.source': 'Wie Vorlage',
    'farbe.hex': 'Feste Farbe',
    'farbe.variable': 'Design-Token',
    'farbe.suche': 'Design-Token suchen …',
    'farbe.lokal': 'Tokens in diesem File',
    'farbe.leer': 'Keine Farb-Tokens gefunden. Library-Tokens erscheinen nur, wenn die Library in diesem File aktiviert ist (Assets → Libraries). Details im Protokoll.',
    'farbe.aktualisieren': 'Aktualisieren',
    'farbe.laden': 'Design-Tokens werden geladen …',
    'farbe.angleichen': 'Vorlage an diese Farbe binden',
    'farbe.gewaehlt': 'Gewählt',
    'farbe.unaufloesbar': 'Design-Token nicht auflösbar.',

    'cfg.schreiben': 'Schreiben',
    'chk.frameUmwandeln': 'Frames in Komponenten umwandeln',
    'tip.frameUmwandeln': 'Beim Bauen darf ein Frame im Master-Maß in eine Komponente umgewandelt werden. Aus ist konservativ: das Plugin meldet dann einen Fehler statt zu ändern.',
    'chk.strokeHeimAnlegen': 'Frame für Stroke-Fassungen anlegen',
    'tip.strokeHeimAnlegen': 'Legt bei Bedarf einen Frame „Icon Pipeline · Stroke“ neben der Vorlage an. Aus: Stroke-Fassungen werden übersprungen.',

    'cfg.datei': 'Konfigurationsdatei',
    'btn.exportKonfig': 'Exportieren',
    'file.importKonfig': 'Importieren',
    'toast.exportiert': 'Konfiguration exportiert',
    'toast.importiert': 'Konfiguration importiert',
    'toast.importFehler': 'Datei ist keine gültige Konfiguration',
    'btn.vorschauMit': 'Vorschau mit diesen Einstellungen',
    'chip.ungespeichert': 'ungespeichert',

    'btn.speichern': 'Speichern',
    'btn.zuruecksetzen': 'Zurücksetzen',
    'dlg.reset.titel': 'Einstellungen zurücksetzen',
    'dlg.reset.text': 'Auf welches Profil soll zurückgesetzt werden? Die aktuelle Konfiguration wird ersetzt.',
    'profil.zds': 'ZDS',
    'profil.generic': 'Allgemein',
    'profil.material': 'Material',
    'profil.lucide': 'Lucide',
    'profil.apple': 'Apple',
    'btn.resetOk': 'Zurücksetzen',
    'fehler.kopf': 'Angepasst beim Prüfen:',
    'toast.gespeichert': 'Einstellungen gespeichert',

    'ber.aktionen': 'Bericht',
    'btn.bericht': 'Bericht erstellen',
    'btn.csv': 'CSV',
    'ber.leer': 'Noch kein Bericht. „Bericht erstellen“ misst alle Icons der Library.',
    'ber.zeit': 'Stand {zeit}',
    'ber.icons': 'Icons',
    'ber.ohneSet': 'ohne Set',
    'ber.veraltet': 'veraltet',
    'ber.treueMittel': 'Treue ⌀',
    'ber.keylineOk': 'Keyline ok',
    'ber.spalteName': 'Icon',
    'ber.tipTreue': 'Treue: RMS-Abweichung der 1×-Rasterung von der idealen Kante. Kleiner ist besser. Grün ab 0, rot ab 0,15.',
    'ber.chipOhneSet': 'kein Set',
    'ber.chipVeraltet': 'veraltet',
    'ber.keineDaten': '—',
    'ber.sortieren': 'Klick: nach dieser Spalte sortieren',
    'ber.export': 'Export',
    'ber.umfang': 'Umfang',
    'ber.umfangAlle': 'Alle',
    'ber.umfangAuswahl': 'Auswahl',
    'chk.sprite': 'Sprite zusätzlich',
    'tip.sprite': 'Legt zusätzlich eine sprite.svg mit einem <symbol> je Icon und Größe ins ZIP.',
    'btn.svgExport': 'SVG-Export',
    'ber.exportFehlt': 'Ohne Set — nicht exportiert:',
    'ber.exportLeer': 'Nichts zu exportieren.',
    'toast.csv': 'CSV heruntergeladen',
    'toast.zip': 'ZIP heruntergeladen'
  },
  en: {
    'titel': 'Icon Pipeline',
    'tab.icon': 'Icon',
    'tab.cfg': 'Settings',
    'tab.bericht': 'Report',
    'adapter.zds': 'ZDS',
    'adapter.frei': 'Free',

    'auswahl.leer': 'Select an icon …',
    'auswahl.tip': 'Click: reveal on canvas',
    'btn.vorschau': 'Preview',
    'btn.bauen': 'Build icon',
    'tip.snap': 'Snaps straight edges and curve extrema to the configured grid. The AA oracle keeps whichever version is sharper. Applies to single builds and to “Rebuild all”.',
    'chk.snap': 'Pixel snapping',
    'tip.stroke': 'Unflattened version next to the source, edge-identical to the result. Not published.',
    'chk.stroke': 'Keep stroke version',
    'klasse.erkl': 'The class sets the keyline and the fitting axis. Circles need a larger keyline than squares.',
    'klasse.festTip': 'The class comes from the grid of the board.',
    'klasse.wechselnTip': 'Click to switch the class.',
    'klasse.geratenTip': 'Guessed from the aspect ratio — circle or square? Click to decide.',

    'umf.icon': 'This icon',
    'umf.library': 'Whole library',
    'btn.audit': 'Check',
    'btn.alle': 'Build all',
    'btn.undo': 'Undo',
    'btn.undoN': 'Undo ({n})',
    'tip.undo': 'One step = one icon.',
    'btn.abbrechen': 'Cancel',

    'dlg.plan.titelAlle': 'Rebuild all icons?',
    'dlg.plan.titelEins': 'Build icon?',
    'dlg.plan.textAlle': 'Dry run — nothing has been changed yet. This is what will happen:',
    'dlg.plan.textEins': 'Dry run — nothing has been changed yet.',
    'dlg.plan.leer': 'Nothing to build.',
    'plan.aendern': 'update',
    'plan.neu': 'new',
    'plan.fehlen': 'missing: {liste}',
    'plan.fremd': 'foreign: {liste}',
    'plan.instanzen': '{n} instances',
    'plan.instanzenUnbekannt': 'instances ?',
    'plan.gesperrt': 'locked',
    'plan.summe': '{aendern} to update · {neu} new · {fehlen} variants missing · {gesperrt} locked · {instanzen} instances',
    'plan.strokeHeim': 'A frame for stroke versions will be created.',
    'btn.planBauen': 'Build',
    'chk.trockenlaufEinzel': 'Skip dry run for single builds',

    'leer.karte': 'Select a card on the ZDS board.',
    'leer.kurz': 'Select a source on the canvas — or switch to “Whole library”.',
    'btn.beispiel': 'Create example icon',

    'diff.nuralt': 'no existing set',
    'zoom.kleiner': 'smaller',
    'zoom.groesser': 'larger',

    'zelle.keyline': 'keyline {ist}/{soll}',
    'zelle.gerastet': '{n} edges snapped',

    'log.titel': 'Log',
    'btn.leeren': 'Clear',
    'log.leer': 'Nothing has run yet.',
    'log.zeigen': 'show',

    'cfg.allgemein': 'General',
    'cfg.adapter': 'Adapter',
    'cfg.sprache': 'Language',
    'cfg.variantenProperty': 'Variant property',
    'opt.auto': 'automatic',
    'opt.zds': 'ZDS',
    'opt.frei': 'Free',
    'opt.de': 'German',
    'opt.en': 'English',

    'cfg.master': 'Master',
    'cfg.masterGroesse': 'Size',
    'cfg.masterKontur': 'Stroke width (px)',
    'cfg.keylines': 'Keyline (icon body)',

    'cfg.groessen': 'Sizes',
    'cfg.N': 'N (px)',
    'cfg.kontur': 'Stroke width (px)',
    'cfg.raster': 'Snap edges to',
    'cfg.rasterGrob': 'Prefer whole pixels',
    'cfg.radiusModus': 'Corner radii',
    'cfg.radiusWert': 'Radius (px)',
    'cfg.radiusMin': 'Minimum radius (px)',
    'cfg.standard': 'Default',
    'cfg.entfernen': 'Remove size',
    'cfg.keylinesAuf': 'Keyline (icon body)',
    'cfg.keylinesProp': 'recompute proportionally',
    'cfg.keylinesLegende': 'Box {N} px · pixel grid · shape classes: Square, Circular, Wide, Tall',
    'cfg.keylinesHinweis': 'The keyline is the size of the icon body inside the {N} px box. It follows N automatically until you edit it by hand.',
    'cfg.keylineUnplausibel': 'Keyline {wert} does not fit N = {N} (expected between {min} and {N}).',
    'btn.groesseHinzu': 'Add size',
    'opt.aus': 'off',
    'radius.proportional': 'scale proportionally',
    'radius.fest': 'fixed value',
    'radius.keine': 'no rounding',

    'cfg.farbe': 'Color',
    'farbe.source': 'Like source',
    'farbe.hex': 'Fixed color',
    'farbe.variable': 'Design token',
    'farbe.suche': 'Search design token …',
    'farbe.lokal': 'Tokens in this file',
    'farbe.leer': 'No color tokens found. Library tokens only appear when the library is enabled in this file (Assets → Libraries). See the log for details.',
    'farbe.aktualisieren': 'Refresh',
    'farbe.laden': 'Loading design tokens …',
    'farbe.angleichen': 'Bind source to this color',
    'farbe.gewaehlt': 'Selected',
    'farbe.unaufloesbar': 'Design token cannot be resolved.',

    'cfg.schreiben': 'Writing',
    'chk.frameUmwandeln': 'Convert frames into components',
    'tip.frameUmwandeln': 'Allows a frame at master size to be converted into a component while building. Off is conservative: the plugin reports an error instead of changing anything.',
    'chk.strokeHeimAnlegen': 'Create frame for stroke versions',
    'tip.strokeHeimAnlegen': 'Creates a frame “Icon Pipeline · Stroke” next to the source when needed. Off: stroke versions are skipped.',

    'cfg.datei': 'Configuration file',
    'btn.exportKonfig': 'Export',
    'file.importKonfig': 'Import',
    'toast.exportiert': 'Configuration exported',
    'toast.importiert': 'Configuration imported',
    'toast.importFehler': 'File is not a valid configuration',
    'btn.vorschauMit': 'Preview with these settings',
    'chip.ungespeichert': 'unsaved',

    'btn.speichern': 'Save',
    'btn.zuruecksetzen': 'Reset',
    'dlg.reset.titel': 'Reset settings',
    'dlg.reset.text': 'Which profile should be restored? The current configuration is replaced.',
    'profil.zds': 'ZDS',
    'profil.generic': 'Generic',
    'profil.material': 'Material',
    'profil.lucide': 'Lucide',
    'profil.apple': 'Apple',
    'btn.resetOk': 'Reset',
    'fehler.kopf': 'Adjusted while checking:',
    'toast.gespeichert': 'Settings saved',

    'ber.aktionen': 'Report',
    'btn.bericht': 'Create report',
    'btn.csv': 'CSV',
    'ber.leer': 'No report yet. “Create report” measures every icon in the library.',
    'ber.zeit': 'As of {zeit}',
    'ber.icons': 'Icons',
    'ber.ohneSet': 'without set',
    'ber.veraltet': 'outdated',
    'ber.treueMittel': 'Fidelity ⌀',
    'ber.keylineOk': 'Keylines ok',
    'ber.spalteName': 'Icon',
    'ber.tipTreue': 'Fidelity: RMS deviation of the 1× rasterization from the ideal edge. Smaller is better. Green at 0, red from 0.15.',
    'ber.chipOhneSet': 'no set',
    'ber.chipVeraltet': 'outdated',
    'ber.keineDaten': '—',
    'ber.sortieren': 'Click: sort by this column',
    'ber.export': 'Export',
    'ber.umfang': 'Scope',
    'ber.umfangAlle': 'All',
    'ber.umfangAuswahl': 'Selection',
    'chk.sprite': 'Include sprite',
    'tip.sprite': 'Adds a sprite.svg with one <symbol> per icon and size to the ZIP.',
    'btn.svgExport': 'SVG export',
    'ber.exportFehlt': 'No set — not exported:',
    'ber.exportLeer': 'Nothing to export.',
    'toast.csv': 'CSV downloaded',
    'toast.zip': 'ZIP downloaded'
  }
};
