// Wörterbuch (de/en) — Basis. Weitere Dateien in diesem Ordner werden tief gemischt.
export default {
  de: {
    'titel': 'Icon Pipeline',
    'tab.icon': 'Icon',
    'tab.cfg': 'Einstellungen',
    'tab.bericht': 'Bericht',
    'adapter.zds': 'ZDS',
    'adapter.frei': 'Frei',

    'gruppe.icon': 'Icon',
    'auswahl.leer': 'Icon auswählen …',
    'auswahl.tip': 'Klick: im Canvas zeigen',
    'btn.vorschau': 'Vorschau',
    'btn.bauen': 'Icon bauen',
    'tip.snap': 'Gerade Kanten und Kurven-Scheitel aufs eingestellte Raster. Das AA-Orakel behält automatisch die schärfere Fassung. Gilt fürs Durchziehen und für „Alle neu bauen“.',
    'chk.snap': 'Pixel-Snapping',
    'tip.stroke': 'Ungeplättete Fassung neben der Source, kantenidentisch zum Ergebnis. Wird nicht publiziert.',
    'chk.stroke': 'Stroke-Fassung ablegen',
    'klasse.label': 'Klasse',
    'klasse.geraten': 'geraten',

    'gruppe.library': 'Library — alle Icons',
    'btn.audit': 'Audit',
    'btn.alle': 'Alle neu bauen',
    'btn.abbrechen': 'Abbrechen',
    'btn.abbrechenLauf': 'Lauf abbrechen',

    'dlg.plan.titelAlle': 'Alle Icons neu bauen?',
    'dlg.plan.titelEins': 'Icon bauen?',
    'dlg.plan.textAlle': 'Trockenlauf — noch wurde nichts verändert. Das steht an:',
    'dlg.plan.textEins': 'Trockenlauf — noch wurde nichts verändert.',
    'dlg.plan.leer': 'Nichts zu bauen.',
    'plan.aendern': 'ändern',
    'plan.neu': 'neu',
    'plan.fehlen': 'fehlt: {liste}',
    'plan.fremd': 'fremd: {liste}',
    'plan.instanzen': '{n} Instanzen',
    'plan.instanzenUnbekannt': 'Instanzen ?',
    'plan.gesperrt': 'gesperrt',
    'plan.summe': '{aendern} ändern · {neu} neu · {fehlen} Varianten fehlen · {gesperrt} gesperrt · {instanzen} Instanzen',
    'plan.strokeHeim': 'Ein Frame für Stroke-Fassungen wird angelegt.',
    'btn.planBauen': 'Bauen',
    'chk.trockenlaufEinzel': 'Trockenlauf beim Einzelbau überspringen',

    'leer.titel': 'So funktioniert es',
    'leer.master': 'Master-Komponente: eine quadratische Komponente in der Master-Größe enthält die Vektoren des Icons.',
    'leer.keyline': 'Keyline: das Sollmaß des Icon-Körpers je Formklasse. Daraus wird jede Zielgröße berechnet.',
    'leer.raster': 'Raster & Snapping: Kanten werden aufs eingestellte Pixelraster gezogen, das AA-Orakel behält die schärfere Fassung.',
    'leer.karte': 'Wähle eine Karte auf dem ZDS-Board aus.',
    'btn.beispiel': 'Beispiel-Icon anlegen',

    'diff.vektor': 'Vektor',
    'diff.aktuell': 'aktuell',
    'diff.neu': 'neu',
    'diff.dunkel': 'dunkler Grund',
    'diff.pixel': 'Pixelansicht',
    'diff.rasterung': 'Rasterung',
    'diff.schaerfe': 'weniger AA = schärfer',
    'diff.differenz': 'Differenz',
    'diff.weg': 'nur alt',
    'diff.dazu': 'nur neu',
    'diff.nuralt': 'kein bestehendes Set',
    'zoom.kleiner': 'kleiner',
    'zoom.groesser': 'größer',
    'zoom.zurueck': 'Doppelklick: zurück auf 6×',

    'zelle.keyline': 'Keyline {ist}/{soll}',
    'zelle.masse': 'Kontur {k} · Raster {r}',
    'zelle.gerastet': '{n} Kanten gerastet',
    'zelle.radius': 'Radius {v}',
    'zelle.neu': 'neu',
    'pixel.aa': 'AA {aa} %',
    'pixel.alt': 'aktuell {aa} %',
    'pixel.hint': 'Hinting: {v}',
    'hint.fehler': 'Fehler −{d} %',
    'hint.gleich': 'gleichwertig',
    'hint.ohne': 'ohne Wirkung',

    'log.titel': 'Protokoll',
    'btn.leeren': 'Leeren',
    'log.leer': 'Noch nichts gelaufen.',
    'log.zeigen': 'zeigen',

    'cfg.allgemein': 'Allgemein',
    'cfg.adapter': 'Adapter',
    'cfg.sprache': 'Sprache',
    'cfg.variantenProperty': 'Variantenproperty',
    'opt.auto': 'automatisch',
    'opt.zds': 'ZDS',
    'opt.frei': 'Frei',
    'opt.de': 'Deutsch',
    'opt.en': 'Englisch',

    'cfg.master': 'Master',
    'cfg.masterGroesse': 'Größe',
    'cfg.masterKontur': 'Kontur',
    'cfg.keylines': 'Keylines',

    'cfg.groessen': 'Größen',
    'cfg.N': 'N (px)',
    'cfg.kontur': 'Kontur',
    'cfg.raster': 'Raster',
    'cfg.rasterGrob': 'Grob',
    'cfg.radiusModus': 'Radius',
    'cfg.radiusWert': 'Wert',
    'cfg.radiusMin': 'Min',
    'cfg.standard': 'Standard',
    'cfg.entfernen': 'Größe entfernen',
    'cfg.keylinesAuf': 'Keylines',
    'cfg.keylinesProp': 'proportional neu berechnen',
    'cfg.keylinesLegende': 'Kasten {N} px · Pixelraster · Formklassen: Square, Circular, Wide, Tall',
    'cfg.keylinesHinweis': 'Die Keyline ist die Größe des Icon-Körpers im {N}-px-Kasten. Sie folgt N automatisch, bis du sie von Hand änderst.',
    'cfg.keylineUnplausibel': 'Keyline {wert} passt nicht zu N = {N} (erwartet zwischen {min} und {N}).',
    'btn.groesseHinzu': 'Größe hinzufügen',
    'opt.aus': 'aus',
    'radius.proportional': 'proportional',
    'radius.fest': 'fest',
    'radius.keine': 'keine',

    'cfg.farbe': 'Farbe',
    'farbe.source': 'Source',
    'farbe.hex': 'Hex',
    'farbe.variable': 'Variable',
    'farbe.suche': 'Variable suchen …',
    'farbe.lokal': 'Lokale Variablen',
    'farbe.leer': 'Keine Farbvariablen gefunden. Library-Variablen erscheinen nur, wenn die Library in diesem File aktiviert ist (Assets → Libraries). Details im Protokoll.',
    'farbe.aktualisieren': 'Aktualisieren',
    'farbe.laden': 'Variablen werden geladen …',
    'farbe.angleichen': 'Source-Farbe angleichen',
    'farbe.gewaehlt': 'Gewählt',
    'farbe.unaufloesbar': 'Variable nicht auflösbar.',

    'cfg.schreiben': 'Schreiben',
    'chk.frameUmwandeln': 'Frames in Komponenten umwandeln',
    'tip.frameUmwandeln': 'Beim Bauen darf ein Frame im Master-Maß in eine Komponente umgewandelt werden. Aus ist konservativ: das Plugin meldet dann einen Fehler statt zu ändern.',
    'chk.strokeHeimAnlegen': 'Frame für Stroke-Fassungen anlegen',
    'tip.strokeHeimAnlegen': 'Legt bei Bedarf einen Frame „Icon Pipeline · Stroke“ neben der Source an. Aus: Stroke-Fassungen werden übersprungen.',

    'cfg.datei': 'Konfigurationsdatei',
    'btn.exportKonfig': 'Exportieren',
    'file.importKonfig': 'Importieren',
    'toast.exportiert': 'Konfiguration exportiert',
    'toast.importiert': 'Konfiguration importiert',
    'toast.importFehler': 'Datei ist keine gültige Konfiguration',
    'btn.vorschauMit': 'Vorschau mit diesen Einstellungen',
    'chip.ungespeichert': 'ungespeichert',

    'btn.speichern': 'Speichern',
    'btn.zuruecksetzen': 'Zurücksetzen',
    'dlg.reset.titel': 'Einstellungen zurücksetzen',
    'dlg.reset.text': 'Auf welches Profil soll zurückgesetzt werden? Die aktuelle Konfiguration wird ersetzt.',
    'profil.zds': 'ZDS',
    'profil.generic': 'Allgemein',
    'profil.material': 'Material',
    'profil.lucide': 'Lucide',
    'profil.apple': 'Apple',
    'btn.resetOk': 'Zurücksetzen',
    'fehler.kopf': 'Angepasst beim Prüfen:',
    'toast.gespeichert': 'Einstellungen gespeichert',

    'ber.aktionen': 'Bericht',
    'btn.bericht': 'Bericht erstellen',
    'btn.csv': 'CSV',
    'ber.leer': 'Noch kein Bericht. „Bericht erstellen“ misst alle Icons der Library.',
    'ber.zeit': 'Stand {zeit}',
    'ber.icons': 'Icons',
    'ber.ohneSet': 'ohne Set',
    'ber.veraltet': 'veraltet',
    'ber.treueMittel': 'Treue ⌀',
    'ber.keylineOk': 'Keyline ok',
    'ber.spalteName': 'Icon',
    'ber.tipTreue': 'Treue: RMS-Abweichung der 1×-Rasterung von der idealen Kante. Kleiner ist besser. Grün ab 0, rot ab 0,15.',
    'ber.chipOhneSet': 'kein Set',
    'ber.chipVeraltet': 'veraltet',
    'ber.keineDaten': '—',
    'ber.sortieren': 'Klick: nach dieser Spalte sortieren',
    'ber.export': 'Export',
    'ber.umfang': 'Umfang',
    'ber.umfangAlle': 'Alle',
    'ber.umfangAuswahl': 'Auswahl',
    'chk.sprite': 'Sprite zusätzlich',
    'tip.sprite': 'Legt zusätzlich eine sprite.svg mit einem <symbol> je Icon und Größe ins ZIP.',
    'btn.svgExport': 'SVG-Export',
    'ber.exportFehlt': 'Ohne Set — nicht exportiert:',
    'ber.exportLeer': 'Nichts zu exportieren.',
    'toast.csv': 'CSV heruntergeladen',
    'toast.zip': 'ZIP heruntergeladen'
  },
  en: {
    'titel': 'Icon Pipeline',
    'tab.icon': 'Icon',
    'tab.cfg': 'Settings',
    'tab.bericht': 'Report',
    'adapter.zds': 'ZDS',
    'adapter.frei': 'Free',

    'gruppe.icon': 'Icon',
    'auswahl.leer': 'Select an icon …',
    'auswahl.tip': 'Click: reveal on canvas',
    'btn.vorschau': 'Preview',
    'btn.bauen': 'Build icon',
    'tip.snap': 'Snaps straight edges and curve extrema to the configured grid. The AA oracle keeps whichever version is sharper. Applies to single builds and to “Rebuild all”.',
    'chk.snap': 'Pixel snapping',
    'tip.stroke': 'Unflattened version next to the source, edge-identical to the result. Not published.',
    'chk.stroke': 'Keep stroke version',
    'klasse.label': 'Class',
    'klasse.geraten': 'guessed',

    'gruppe.library': 'Library — all icons',
    'btn.audit': 'Audit',
    'btn.alle': 'Rebuild all',
    'btn.abbrechen': 'Cancel',
    'btn.abbrechenLauf': 'Cancel run',

    'dlg.plan.titelAlle': 'Rebuild all icons?',
    'dlg.plan.titelEins': 'Build icon?',
    'dlg.plan.textAlle': 'Dry run — nothing has been changed yet. This is what will happen:',
    'dlg.plan.textEins': 'Dry run — nothing has been changed yet.',
    'dlg.plan.leer': 'Nothing to build.',
    'plan.aendern': 'update',
    'plan.neu': 'new',
    'plan.fehlen': 'missing: {liste}',
    'plan.fremd': 'foreign: {liste}',
    'plan.instanzen': '{n} instances',
    'plan.instanzenUnbekannt': 'instances ?',
    'plan.gesperrt': 'locked',
    'plan.summe': '{aendern} to update · {neu} new · {fehlen} variants missing · {gesperrt} locked · {instanzen} instances',
    'plan.strokeHeim': 'A frame for stroke versions will be created.',
    'btn.planBauen': 'Build',
    'chk.trockenlaufEinzel': 'Skip dry run for single builds',

    'leer.titel': 'How it works',
    'leer.master': 'Master component: a square component at the master size holds the icon’s vectors.',
    'leer.keyline': 'Keyline: the target size of the icon body per shape class. Every output size is derived from it.',
    'leer.raster': 'Grid & snapping: edges are pulled onto the configured pixel grid, the AA oracle keeps whichever version is sharper.',
    'leer.karte': 'Select a card on the ZDS board.',
    'btn.beispiel': 'Create example icon',

    'diff.vektor': 'Vector',
    'diff.aktuell': 'current',
    'diff.neu': 'new',
    'diff.dunkel': 'dark background',
    'diff.pixel': 'Pixel view',
    'diff.rasterung': 'Rasterization',
    'diff.schaerfe': 'less AA = sharper',
    'diff.differenz': 'Difference',
    'diff.weg': 'old only',
    'diff.dazu': 'new only',
    'diff.nuralt': 'no existing set',
    'zoom.kleiner': 'smaller',
    'zoom.groesser': 'larger',
    'zoom.zurueck': 'Double click: back to 6×',

    'zelle.keyline': 'keyline {ist}/{soll}',
    'zelle.masse': 'stroke {k} · grid {r}',
    'zelle.gerastet': '{n} edges snapped',
    'zelle.radius': 'radius {v}',
    'zelle.neu': 'new',
    'pixel.aa': 'AA {aa} %',
    'pixel.alt': 'current {aa} %',
    'pixel.hint': 'Hinting: {v}',
    'hint.fehler': 'error −{d} %',
    'hint.gleich': 'equivalent',
    'hint.ohne': 'no effect',

    'log.titel': 'Log',
    'btn.leeren': 'Clear',
    'log.leer': 'Nothing has run yet.',
    'log.zeigen': 'show',

    'cfg.allgemein': 'General',
    'cfg.adapter': 'Adapter',
    'cfg.sprache': 'Language',
    'cfg.variantenProperty': 'Variant property',
    'opt.auto': 'automatic',
    'opt.zds': 'ZDS',
    'opt.frei': 'Free',
    'opt.de': 'German',
    'opt.en': 'English',

    'cfg.master': 'Master',
    'cfg.masterGroesse': 'Size',
    'cfg.masterKontur': 'Stroke',
    'cfg.keylines': 'Keylines',

    'cfg.groessen': 'Sizes',
    'cfg.N': 'N (px)',
    'cfg.kontur': 'Stroke',
    'cfg.raster': 'Grid',
    'cfg.rasterGrob': 'Coarse',
    'cfg.radiusModus': 'Radius',
    'cfg.radiusWert': 'Value',
    'cfg.radiusMin': 'Min',
    'cfg.standard': 'Default',
    'cfg.entfernen': 'Remove size',
    'cfg.keylinesAuf': 'Keylines',
    'cfg.keylinesProp': 'recompute proportionally',
    'cfg.keylinesLegende': 'Box {N} px · pixel grid · shape classes: Square, Circular, Wide, Tall',
    'cfg.keylinesHinweis': 'The keyline is the size of the icon body inside the {N} px box. It follows N automatically until you edit it by hand.',
    'cfg.keylineUnplausibel': 'Keyline {wert} does not fit N = {N} (expected between {min} and {N}).',
    'btn.groesseHinzu': 'Add size',
    'opt.aus': 'off',
    'radius.proportional': 'proportional',
    'radius.fest': 'fixed',
    'radius.keine': 'none',

    'cfg.farbe': 'Color',
    'farbe.source': 'Source',
    'farbe.hex': 'Hex',
    'farbe.variable': 'Variable',
    'farbe.suche': 'Search variable …',
    'farbe.lokal': 'Local variables',
    'farbe.leer': 'No color variables found. Library variables only appear when the library is enabled in this file (Assets → Libraries). See the log for details.',
    'farbe.aktualisieren': 'Refresh',
    'farbe.laden': 'Loading variables …',
    'farbe.angleichen': 'Match source color',
    'farbe.gewaehlt': 'Selected',
    'farbe.unaufloesbar': 'Variable cannot be resolved.',

    'cfg.schreiben': 'Writing',
    'chk.frameUmwandeln': 'Convert frames into components',
    'tip.frameUmwandeln': 'Allows a frame at master size to be converted into a component while building. Off is conservative: the plugin reports an error instead of changing anything.',
    'chk.strokeHeimAnlegen': 'Create frame for stroke versions',
    'tip.strokeHeimAnlegen': 'Creates a frame “Icon Pipeline · Stroke” next to the source when needed. Off: stroke versions are skipped.',

    'cfg.datei': 'Configuration file',
    'btn.exportKonfig': 'Export',
    'file.importKonfig': 'Import',
    'toast.exportiert': 'Configuration exported',
    'toast.importiert': 'Configuration imported',
    'toast.importFehler': 'File is not a valid configuration',
    'btn.vorschauMit': 'Preview with these settings',
    'chip.ungespeichert': 'unsaved',

    'btn.speichern': 'Save',
    'btn.zuruecksetzen': 'Reset',
    'dlg.reset.titel': 'Reset settings',
    'dlg.reset.text': 'Which profile should be restored? The current configuration is replaced.',
    'profil.zds': 'ZDS',
    'profil.generic': 'Generic',
    'profil.material': 'Material',
    'profil.lucide': 'Lucide',
    'profil.apple': 'Apple',
    'btn.resetOk': 'Reset',
    'fehler.kopf': 'Adjusted while checking:',
    'toast.gespeichert': 'Settings saved',

    'ber.aktionen': 'Report',
    'btn.bericht': 'Create report',
    'btn.csv': 'CSV',
    'ber.leer': 'No report yet. “Create report” measures every icon in the library.',
    'ber.zeit': 'As of {zeit}',
    'ber.icons': 'Icons',
    'ber.ohneSet': 'without set',
    'ber.veraltet': 'outdated',
    'ber.treueMittel': 'Fidelity ⌀',
    'ber.keylineOk': 'Keylines ok',
    'ber.spalteName': 'Icon',
    'ber.tipTreue': 'Fidelity: RMS deviation of the 1× rasterization from the ideal edge. Smaller is better. Green at 0, red from 0.15.',
    'ber.chipOhneSet': 'no set',
    'ber.chipVeraltet': 'outdated',
    'ber.keineDaten': '—',
    'ber.sortieren': 'Click: sort by this column',
    'ber.export': 'Export',
    'ber.umfang': 'Scope',
    'ber.umfangAlle': 'All',
    'ber.umfangAuswahl': 'Selection',
    'chk.sprite': 'Include sprite',
    'tip.sprite': 'Adds a sprite.svg with one <symbol> per icon and size to the ZIP.',
    'btn.svgExport': 'SVG export',
    'ber.exportFehlt': 'No set — not exported:',
    'ber.exportLeer': 'Nothing to export.',
    'toast.csv': 'CSV downloaded',
    'toast.zip': 'ZIP downloaded'
  }
};
