// Wörterbuch — Bericht, Protokoll, Vorschau, Fortschritt (Runde 4, Paket UI-2).
// Diese Datei wird NACH 10-basis.mjs gemischt und überschreibt dort gesetzte
// Schlüssel bewusst: die Begriffe folgen der Tabelle in ARCHITEKTUR.md §27
// (Rasterfehler, weiche Pixel, Maß stimmt, Vorlage).
export default {
  de: {
    // ---- Vorschau ---------------------------------------------------------
    'v.titel': 'Vorschau · {name}',
    'modus.wischen': 'Wischen',
    'modus.neben': 'Nebeneinander',
    'tip.vergleich': 'Nebeneinander: zwei Kacheln je Größe. Wischen: eine Kachel, der Griff zieht die neue Fassung über die alte.',
    'dar.pixel': 'Pixel',
    'dar.vektor': 'Vektor',
    'tip.darstellung': 'Pixel zeigt die echte Rasterung, pixelgenau hochgezogen. Vektor zeichnet die Geometrie glatt in jeder Zoomstufe.',
    'v.markieren': 'Änderungen markieren',
    'tip.markieren': 'Rahmt in der Nachher-Kachel jeden Bereich ein, dessen Pixel sich geändert haben.',
    'v.verbesserung': 'Verbesserung zeigen',
    'tip.verbesserung': 'Blendet mit dem Regler von vorher nach nachher über — so sieht man, wie die weichen Kanten hart werden.',
    'v.scrubber': 'Vorher → Nachher',
    'v.grund': 'Heller oder dunkler Grund',
    'v.hoehe': 'Höhe der Bühne ziehen',
    'v.legende': 'Markierte Bereiche: Pixel, die das Plugin verändert hat.',
    'pill.vorher': 'Vorher',
    'pill.nachher': 'Nachher',
    'zoom.fit': 'Fit',
    'zoom.fitTitel': 'Alle Größen einpassen (0)',
    'zoom.kleiner': 'kleiner (−)',
    'zoom.groesser': 'größer (+)',
    'urt.neu': 'Neu — noch kein Vergleich',
    'urt.besser': 'Schärfer geworden',
    'urt.gleich': 'Praktisch unverändert',
    'urt.schlechter': 'Weicher geworden',
    'urt.aa': 'Weiche Pixel {alt} % → {neu} %',
    'urt.aaNur': 'Weiche Pixel {neu} %',
    'urt.fehler': 'Rasterfehler {v}',
    'urt.fehlerVgl': 'Rasterfehler {alt} → {neu}',
    'urt.mass': 'Maß stimmt in {n} von {m} Größen',
    'urt.massAb': 'Maß weicht ab in {n} von {m} Größen',
    'urt.gerastet': '{n} Kanten gerastet',
    'fuss.fehler': 'Rasterfehler',
    'fuss.aa': 'Weiche Pixel',
    'fuss.keyline': 'Keyline',
    'reg.kante': 'Kante um {d} px {richtung} gerastet',
    'reg.form': 'Form verändert — {d} px Fläche',
    'reg.links': 'nach links',
    'reg.rechts': 'nach rechts',
    'reg.oben': 'nach oben',
    'reg.unten': 'nach unten',
    'det.titel': 'Details',
    'det.vektor': 'Vektor-Umriss',
    'det.vektorHinweis': 'Vorher grau, Nachher schwarz',
    'det.pixel': 'Pixelraster',
    'det.differenz': 'Differenz',
    'zelle.massOk': 'Maß stimmt',
    'zelle.massAb': 'Maß weicht ab',
    'zelle.kontur': '{k} px Strich',
    'zelle.raster': 'Raster {r}',
    'px.koord': 'x {x} · y {y}',
    'diff.nurNeu': 'nur neu — kein bestehendes Set',

    // ---- Bericht ----------------------------------------------------------
    'ber.veraltet': 'Vorlage geändert',
    'ber.chipVeraltet': 'Vorlage geändert',
    'ber.treueMittel': 'Rasterfehler ⌀',
    'ber.keylineOk': 'Maß stimmt',
    'ber.spalteName': 'Icon',
    'ber.tipTreue': 'Rasterfehler: Abweichung der echten Pixel vom Ideal. 0 = perfekt, unter 0,02 sehr gut, über 0,05 auffällig.',
    'ber.tipAa': 'Weiche Pixel: Anteil halbtransparenter Randpixel. Niedriger ist schärfer, hängt von der Form ab (Kreise haben mehr).',
    'ber.tipMass': 'Maß stimmt: Das Icon füllt das vorgesehene Keyline-Maß.',
    'ber.tipSpalte': '{n} px — Rasterfehler, weiche Pixel, Maß stimmt',
    'ber.legende': 'Rasterfehler = Abweichung der echten Pixel vom Ideal (0 ist perfekt) · weiche Pixel = Anteil halbtransparenter Randpixel · Maß stimmt = Icon füllt die Keyline.',
    'ber.filter': 'Filter',
    'flt.alle': 'Alle',
    'flt.ohneSet': 'ohne Set',
    'flt.veraltet': 'Vorlage geändert',
    'flt.mass': 'Maß-Fehler',
    'flt.schlecht': 'schlechteste 10 %',
    'ber.zaehler': '{n} von {m}',
    'ber.alleSichtbaren': 'alle sichtbaren',
    'ber.keineTreffer': 'Kein Icon passt zu diesem Filter.',
    'ber.umfangAlle': 'Alle',
    'ber.umfangNamen': 'Ausgewählte ({n})',
    'ber.umfangAuswahl': 'Aktuelles Icon',
    'ber.tipUmfang': 'Ausgewählte: die angehakten Zeilen der Tabelle. Aktuelles Icon: die Auswahl im Canvas.',

    // ---- Protokoll --------------------------------------------------------
    'log.suche': 'Protokoll durchsuchen …',
    'log.allgemein': 'Allgemein',
    'log.keineTreffer': 'Nichts passt zu Filter und Suche.',
    'log.filterAlle': 'Alle',
    'log.filterFehler': 'Fehler',
    'log.filterWarn': 'Warnungen',
    'log.filterInfo': 'Hinweise',
    'log.filterOk': 'OK',
    'btn.kopieren': 'Kopieren',
    'toast.logKopiert': 'Protokoll kopiert',
    'toast.logNichts': 'Nichts zu kopieren',
    'log.groesse': '{n} px',
    'log.gruppeTip': '{err} Fehler · {warn} Warnungen · {info} Hinweise',

    // ---- Fortschritt ------------------------------------------------------
    'fort.baue': 'Baue {i}/{n}',
    'fort.rest': 'noch ca. {zeit}',
    'fort.sek': '{n} s',
    'fort.min': '{n} min'
  },
  en: {
    // ---- Preview ----------------------------------------------------------
    'v.titel': 'Preview · {name}',
    'modus.wischen': 'Wipe',
    'modus.neben': 'Side by side',
    'tip.vergleich': 'Side by side: two tiles per size. Wipe: one tile, the handle pulls the new version over the old one.',
    'dar.pixel': 'Pixels',
    'dar.vektor': 'Vector',
    'tip.darstellung': 'Pixels shows the real rasterization, scaled up pixel-exact. Vector draws the geometry smoothly at any zoom.',
    'v.markieren': 'Highlight changes',
    'tip.markieren': 'Outlines every area in the after tile whose pixels changed.',
    'v.verbesserung': 'Show the improvement',
    'tip.verbesserung': 'Fades from before to after with the slider — you can watch the soft edges become crisp.',
    'v.scrubber': 'Before → after',
    'v.grund': 'Light or dark background',
    'v.hoehe': 'Drag to resize the stage',
    'v.legende': 'Highlighted areas: pixels the plugin changed.',
    'pill.vorher': 'Before',
    'pill.nachher': 'After',
    'zoom.fit': 'Fit',
    'zoom.fitTitel': 'Fit all sizes (0)',
    'zoom.kleiner': 'smaller (−)',
    'zoom.groesser': 'larger (+)',
    'urt.neu': 'New — nothing to compare yet',
    'urt.besser': 'Sharper now',
    'urt.gleich': 'Practically unchanged',
    'urt.schlechter': 'Softer now',
    'urt.aa': 'Soft pixels {alt} % → {neu} %',
    'urt.aaNur': 'Soft pixels {neu} %',
    'urt.fehler': 'Raster error {v}',
    'urt.fehlerVgl': 'Raster error {alt} → {neu}',
    'urt.mass': 'Size ok in {n} of {m} sizes',
    'urt.massAb': 'Size differs in {n} of {m} sizes',
    'urt.gerastet': '{n} edges snapped',
    'fuss.fehler': 'Raster error',
    'fuss.aa': 'Soft pixels',
    'fuss.keyline': 'Keyline',
    'reg.kante': 'Edge snapped {d} px {richtung}',
    'reg.form': 'Shape changed — {d} px of area',
    'reg.links': 'left',
    'reg.rechts': 'right',
    'reg.oben': 'up',
    'reg.unten': 'down',
    'det.titel': 'Details',
    'det.vektor': 'Vector outline',
    'det.vektorHinweis': 'Before grey, after black',
    'det.pixel': 'Pixel grid',
    'det.differenz': 'Difference',
    'zelle.massOk': 'Size ok',
    'zelle.massAb': 'Size differs',
    'zelle.kontur': '{k} px stroke',
    'zelle.raster': 'Snap {r}',
    'px.koord': 'x {x} · y {y}',
    'diff.nurNeu': 'new only — no existing set',

    // ---- Report -----------------------------------------------------------
    'ber.veraltet': 'source changed',
    'ber.chipVeraltet': 'source changed',
    'ber.treueMittel': 'Raster error ⌀',
    'ber.keylineOk': 'Size ok',
    'ber.spalteName': 'Icon',
    'ber.tipTreue': 'Raster error: deviation of the real pixels from the ideal. 0 = perfect, below 0.02 very good, above 0.05 noticeable.',
    'ber.tipAa': 'Soft pixels: share of semi-transparent edge pixels. Lower is sharper, depends on the shape (circles have more).',
    'ber.tipMass': 'Size ok: the icon fills the intended keyline size.',
    'ber.tipSpalte': '{n} px — raster error, soft pixels, size ok',
    'ber.legende': 'Raster error = deviation of the real pixels from the ideal (0 is perfect) · soft pixels = share of semi-transparent edge pixels · size ok = the icon fills the keyline.',
    'ber.filter': 'Filter',
    'flt.alle': 'All',
    'flt.ohneSet': 'without set',
    'flt.veraltet': 'source changed',
    'flt.mass': 'size errors',
    'flt.schlecht': 'worst 10 %',
    'ber.zaehler': '{n} of {m}',
    'ber.alleSichtbaren': 'all visible',
    'ber.keineTreffer': 'No icon matches this filter.',
    'ber.umfangAlle': 'All',
    'ber.umfangNamen': 'Selected ({n})',
    'ber.umfangAuswahl': 'Current icon',
    'ber.tipUmfang': 'Selected: the ticked rows of the table. Current icon: the canvas selection.',

    // ---- Log --------------------------------------------------------------
    'log.suche': 'Search the log …',
    'log.allgemein': 'General',
    'log.keineTreffer': 'Nothing matches filter and search.',
    'log.filterAlle': 'All',
    'log.filterFehler': 'Errors',
    'log.filterWarn': 'Warnings',
    'log.filterInfo': 'Notes',
    'log.filterOk': 'OK',
    'btn.kopieren': 'Copy',
    'toast.logKopiert': 'Log copied',
    'toast.logNichts': 'Nothing to copy',
    'log.groesse': '{n} px',
    'log.gruppeTip': '{err} errors · {warn} warnings · {info} notes',

    // ---- Progress ---------------------------------------------------------
    'fort.baue': 'Building {i}/{n}',
    'fort.rest': '~{zeit} left',
    'fort.sek': '{n} s',
    'fort.min': '{n} min'
  }
};
