// Wörterbuch — Bericht, Protokoll, Vorschau, Fortschritt (Runde 4, Paket UI-2).
// Diese Datei wird NACH 10-basis.mjs gemischt und überschreibt dort gesetzte
// Schlüssel bewusst: die Begriffe folgen der Tabelle in ARCHITEKTUR.md §27
// (Rasterfehler, weiche Kanten (Anti-Aliasing), Maß stimmt, Vorlage).
export default {
  de: {
    // ---- Vorschau ---------------------------------------------------------
    'modus.vn': '◧',
    'modus.ueberlagern': '◉',
    'tip.vn': 'Vorher/Nachher: eine Kachel, der Trenner zieht das Ergebnis über die Vergleichsbasis.',
    'tip.ueberlagern': 'Überlagern: beide Fassungen übereinander — Unterschiede farbig, Deckung grau.',
    'dar.pixel': 'Pixel',
    'dar.vektor': 'Vektor',
    'tip.darstellung': 'Pixel zeigt die echte Rasterung, pixelgenau hochgezogen. Vektor rastert die Geometrie in jeder Zoomstufe neu.',
    'v.punkte': 'Punkte & Kanten',
    'tip.punkte': 'Zeigt die Kontur vorher gestrichelt, die Kontur nachher durchgezogen und jeden Vektorpunkt, der gewandert ist.',
    'v.flaechen': 'Flächen',
    'tip.flaechen': 'Färbt die Flächen ein, die weggefallen (orange) oder hinzugekommen (blau) sind.',
    'v.basis': 'Vergleich mit',
    'v.basisOhne': 'ohne Snapping',
    'v.basisAlt': 'Library-Stand',
    'tip.basis': 'Ohne Snapping zeigt, was das Plugin gerade verbessert. Library-Stand vergleicht mit dem, was im File liegt.',
    'v.scrubber': 'Vorher · Nachher',
    'v.gewichtung': 'Gewichtung',
    'v.grund': 'Heller oder dunkler Grund',
    'v.hoehe': 'Höhe der Bühne ziehen',
    'tip.retina': 'Zeigt statt der 1×- die 2×-Rasterung — so sieht man, wie das Icon auf einem Retina-Display fällt.',
    'hint.titel': 'Hinting',
    'hint.kanten': 'Gerastete Kanten',
    'hint.geschuetzt': 'Geschützte Knoten',
    'hint.orakel': 'Orakel',
    'hint.orakelSnap': 'Snapping übernommen',
    'hint.orakelFit': 'Fit-Geometrie behalten — Snapping ohne Wirkung',
    'hint.raster': 'Kanten rasten auf',
    'hint.grob': 'ganze Pixel bevorzugt ({v})',
    'hint.phase': 'Phase der Kontur',
    'hint.kontur': 'Strichstärke',
    'hint.radius': 'Eckenradien',
    'pill.vorher': 'Vorher',
    'pill.nachher': 'Nachher',
    'pill.beide': 'Überlagert',
    'pill.snapAn': 'Snapping an',
    'pill.snapAus': 'Snapping aus',
    'leg.weg': 'Fläche entfernt',
    'leg.dazu': 'Fläche hinzugekommen',
    'leg.vorKontur': 'Kontur vorher',
    'leg.punktAlt': 'Punkt vorher',
    'leg.punktNeu': 'Punkt nachher',
    'leg.aus': 'Markierungen aus',
    'v.mehr': 'Weitere Schalter',
    'zoom.fitKurz': 'Fit',
    'zoom.fit': 'Fit',
    'zoom.fitTitel': 'Alle Größen einpassen (0)',
    'zoom.kleiner': 'kleiner (−)',
    'zoom.groesser': 'größer (+)',
    'urt.neu': 'Neu — noch kein Vergleich',
    'urt.besser': 'Schärfer: weiche Kanten {alt} → {neu}',
    'urt.gleich': 'Weiche Kanten unverändert ({neu})',
    'urt.schlechter': 'Weicher: weiche Kanten {alt} → {neu}',
    'urt.fehler': 'Rasterfehler {v}',
    'urt.mass': 'Maß {n}/{m}',
    'urt.gerastet': '{n} Kanten gerastet',
    'urt.punkte': '{n} Punkte gewandert',
    'urt.basisLib': 'Vergleich mit dem Library-Stand',
    'fuss.fehler': 'Rasterfehler',
    'fuss.aa': 'Weiche Kanten (Anti-Aliasing)',
    'fuss.keyline': 'Keyline (Icon-Körper)',
    'fuss.punkte': 'Gewanderte Punkte',
    'fuss.veraendert': 'Veränderte Pixel',
    'fuss.veraendertWert': '{n} ({weg} entfernt, {dazu} neu)',
    'tip.veraendert': 'Pixel, deren Deckung sich geändert hat — gesamt, davon entfernt und hinzugekommen.',
    'pkt.hover': 'Punkt um {d} px {richtung} gerastet',
    'reg.links': 'nach links',
    'reg.rechts': 'nach rechts',
    'reg.oben': 'nach oben',
    'reg.unten': 'nach unten',
    'px.koord': 'x {x} · y {y}',

    // ---- Bericht ----------------------------------------------------------
    'ber.veraltet': 'Vorlage geändert',
    'ber.chipVeraltet': 'Vorlage geändert',
    'ber.treueMittel': 'Rasterfehler ⌀',
    'ber.keylineOk': 'Maß stimmt',
    'ber.spalteName': 'Icon',
    'ber.tipTreue': 'Rasterfehler: Wie stark die gerenderten Pixel vom idealen, scharfen Bild abweichen. 0 = perfekt; unter 0,02 sehr gut.',
    'ber.tipAa': 'Weiche Kanten (Anti-Aliasing): Anteil halbtransparenter Randpixel. Weniger = schärfer; runde Formen haben naturgemäß mehr.',
    'ber.tipMass': 'Keyline (Icon-Körper): das Maß, das der Icon-Körper im Kasten einnimmt. Das Häkchen sagt, ob es stimmt.',
    'ber.tipSpalte': '{n} px — Rasterfehler, weiche Kanten, Maß stimmt',
    'ber.legende': 'Rasterfehler = Abweichung der gerenderten Pixel vom idealen Bild (0 ist perfekt) · weiche Kanten (Anti-Aliasing) = Anteil halbtransparenter Randpixel · Maß stimmt = Icon füllt die Keyline.',
    'flt.alle': 'Alle',
    'flt.ohneSet': 'ohne Set',
    'flt.veraltet': 'Vorlage geändert',
    'flt.mass': 'Maß-Fehler',
    'flt.schlecht': 'schlechteste 10 %',
    'ber.zaehler': '{n} von {m}',
    'ber.alleSichtbaren': 'alle sichtbaren',
    'ber.keineTreffer': 'Kein Icon passt zu diesem Filter.',
    'ber.umfangAlle': 'Alle',
    'ber.umfangNamen': 'Ausgewählte ({n})',
    'ber.umfangAuswahl': 'Aktuelles Icon',
    'ber.tipUmfang': 'Ausgewählte: die angehakten Zeilen der Tabelle. Aktuelles Icon: die Auswahl im Canvas.',

    // ---- Protokoll --------------------------------------------------------
    'log.suche': 'Protokoll durchsuchen …',
    'log.allgemein': 'Allgemein',
    'log.keineTreffer': 'Nichts passt zu Filter und Suche.',
    'log.filterAlle': 'Alle',
    'log.filterFehler': 'Fehler',
    'log.filterWarn': 'Warnungen',
    'log.filterInfo': 'Hinweise',
    'log.filterOk': 'OK',
    'btn.kopieren': 'Kopieren',
    'toast.logKopiert': 'Protokoll kopiert',
    'toast.logNichts': 'Nichts zu kopieren',
    'log.groesse': '{n} px',
    'log.gruppeTip': '{err} Fehler · {warn} Warnungen · {info} Hinweise',

    // ---- Fortschritt ------------------------------------------------------
    'fort.baue': 'Baue {i}/{n}',
    'fort.rest': 'noch ca. {zeit}',
    'fort.sek': '{n} s',
    'fort.min': '{n} min'
  },
  en: {
    // ---- Preview ----------------------------------------------------------
    'modus.vn': '◧',
    'modus.ueberlagern': '◉',
    'tip.vn': 'Before/after: one tile, the divider pulls the result over the comparison base.',
    'tip.ueberlagern': 'Overlay: both versions on top of each other — differences in color, overlap grey.',
    'dar.pixel': 'Pixels',
    'dar.vektor': 'Vector',
    'tip.darstellung': 'Pixels shows the real rasterization, scaled up pixel-exact. Vector re-rasterizes the geometry at every zoom step.',
    'v.punkte': 'Points & edges',
    'tip.punkte': 'Shows the contour before as a dashed line, the contour after as a solid one, and every vector point that moved.',
    'v.flaechen': 'Areas',
    'tip.flaechen': 'Colors the areas that were removed (orange) or added (blue).',
    'v.basis': 'Compare with',
    'v.basisOhne': 'without snapping',
    'v.basisAlt': 'library state',
    'tip.basis': 'Without snapping shows what the plugin is improving right now. Library state compares with what is in the file.',
    'v.scrubber': 'Before · after',
    'v.gewichtung': 'Weighting',
    'v.grund': 'Light or dark background',
    'v.hoehe': 'Drag to resize the stage',
    'tip.retina': 'Shows the 2× rasterization instead of 1× — that is how the icon lands on a Retina display.',
    'hint.titel': 'Hinting',
    'hint.kanten': 'Snapped edges',
    'hint.geschuetzt': 'Protected nodes',
    'hint.orakel': 'Oracle',
    'hint.orakelSnap': 'snapping kept',
    'hint.orakelFit': 'fit geometry kept — snapping had no effect',
    'hint.raster': 'Snap edges to',
    'hint.grob': 'prefers whole pixels ({v})',
    'hint.phase': 'Stroke phase',
    'hint.kontur': 'Stroke width',
    'hint.radius': 'Corner radii',
    'pill.vorher': 'Before',
    'pill.nachher': 'After',
    'pill.beide': 'Overlay',
    'pill.snapAn': 'Snapping on',
    'pill.snapAus': 'Snapping off',
    'leg.weg': 'Area removed',
    'leg.dazu': 'Area added',
    'leg.vorKontur': 'Contour before',
    'leg.punktAlt': 'Point before',
    'leg.punktNeu': 'Point after',
    'leg.aus': 'Markers off',
    'v.mehr': 'More switches',
    'zoom.fitKurz': 'Fit',
    'zoom.fit': 'Fit',
    'zoom.fitTitel': 'Fit all sizes (0)',
    'zoom.kleiner': 'smaller (−)',
    'zoom.groesser': 'larger (+)',
    'urt.neu': 'New — nothing to compare yet',
    'urt.besser': 'Sharper: soft edges {alt} → {neu}',
    'urt.gleich': 'Soft edges unchanged ({neu})',
    'urt.schlechter': 'Softer: soft edges {alt} → {neu}',
    'urt.fehler': 'Raster error {v}',
    'urt.mass': 'Size {n}/{m}',
    'urt.gerastet': '{n} edges snapped',
    'urt.punkte': '{n} points moved',
    'urt.basisLib': 'compared with the library state',
    'fuss.fehler': 'Raster error',
    'fuss.aa': 'Soft edges (anti-aliasing)',
    'fuss.keyline': 'Keyline (icon body)',
    'fuss.punkte': 'Points moved',
    'fuss.veraendert': 'Changed pixels',
    'fuss.veraendertWert': '{n} ({weg} removed, {dazu} new)',
    'tip.veraendert': 'Pixels whose coverage changed — total, of those removed and added.',
    'pkt.hover': 'Point snapped {d} px {richtung}',
    'reg.links': 'left',
    'reg.rechts': 'right',
    'reg.oben': 'up',
    'reg.unten': 'down',
    'px.koord': 'x {x} · y {y}',

    // ---- Report -----------------------------------------------------------
    'ber.veraltet': 'source changed',
    'ber.chipVeraltet': 'source changed',
    'ber.treueMittel': 'Raster error ⌀',
    'ber.keylineOk': 'Size ok',
    'ber.spalteName': 'Icon',
    'ber.tipTreue': 'Raster error: how far the rendered pixels deviate from the ideal, crisp image. 0 = perfect; below 0.02 very good.',
    'ber.tipAa': 'Soft edges (anti-aliasing): share of semi-transparent edge pixels. Less = sharper; round shapes naturally have more.',
    'ber.tipMass': 'Keyline (icon body): the size the icon body occupies inside the box. The tick says whether it matches.',
    'ber.tipSpalte': '{n} px — raster error, soft edges, size ok',
    'ber.legende': 'Raster error = deviation of the rendered pixels from the ideal image (0 is perfect) · soft edges (anti-aliasing) = share of semi-transparent edge pixels · size ok = the icon fills the keyline.',
    'flt.alle': 'All',
    'flt.ohneSet': 'without set',
    'flt.veraltet': 'source changed',
    'flt.mass': 'size errors',
    'flt.schlecht': 'worst 10 %',
    'ber.zaehler': '{n} of {m}',
    'ber.alleSichtbaren': 'all visible',
    'ber.keineTreffer': 'No icon matches this filter.',
    'ber.umfangAlle': 'All',
    'ber.umfangNamen': 'Selected ({n})',
    'ber.umfangAuswahl': 'Current icon',
    'ber.tipUmfang': 'Selected: the ticked rows of the table. Current icon: the canvas selection.',

    // ---- Log --------------------------------------------------------------
    'log.suche': 'Search the log …',
    'log.allgemein': 'General',
    'log.keineTreffer': 'Nothing matches filter and search.',
    'log.filterAlle': 'All',
    'log.filterFehler': 'Errors',
    'log.filterWarn': 'Warnings',
    'log.filterInfo': 'Notes',
    'log.filterOk': 'OK',
    'btn.kopieren': 'Copy',
    'toast.logKopiert': 'Log copied',
    'toast.logNichts': 'Nothing to copy',
    'log.groesse': '{n} px',
    'log.gruppeTip': '{err} errors · {warn} warnings · {info} notes',

    // ---- Progress ---------------------------------------------------------
    'fort.baue': 'Building {i}/{n}',
    'fort.rest': '~{zeit} left',
    'fort.sek': '{n} s',
    'fort.min': '{n} min'
  }
};
