// Wörterbuch — Bericht, Protokoll, Vorschau, Fortschritt (Runde 4, Paket UI-2).
// Diese Datei wird NACH 10-basis.mjs gemischt und überschreibt dort gesetzte
// Schlüssel bewusst: die Begriffe folgen der Tabelle in ARCHITEKTUR.md §27
// (Rasterfehler, weiche Pixel, Maß stimmt, Vorlage).
export default {
  de: {
    // ---- Vorschau ---------------------------------------------------------
    'diff.vergleich': 'Vergleich',
    'modus.ueberlagern': 'Überlagern',
    'modus.wischen': 'Wischen',
    'modus.neben': 'Nebeneinander',
    'modus.blinken': 'Blinken',
    'tip.vergleich': 'Überlagern: beide Fassungen übereinander. Wischen: Regler zieht die neue Fassung über die aktuelle. Nebeneinander: zwei Zellen je Größe. Blinken: Wechsel im Sekundentakt, Leertaste hält an.',
    'wisch.links': 'aktuell',
    'wisch.rechts': 'neu',
    'blink.hinweis': 'Leertaste hält den Wechsel an',
    'blink.pausiert': 'angehalten',
    'zoom.fit': 'Fit',
    'zoom.fitTitel': 'Alle Größen nebeneinander einpassen',
    'zoom.tasten': 'Tasten + − 0, Strg+Rad zoomt',
    'zelle.massOk': 'Maß stimmt',
    'zelle.massAb': 'Maß weicht ab',
    'zelle.kontur': '{k} px Strich',
    'zelle.raster': 'Raster {r}',
    'zelle.tipVorlage': 'Vorlage {name}',
    'px.koord': 'x {x} · y {y}',
    'px.gruppe': 'Pixelansicht',
    'px.differenz': 'Differenz',
    'diff.nurNeu': 'nur neu — kein bestehendes Set',

    // ---- Bericht ----------------------------------------------------------
    'ber.veraltet': 'Vorlage geändert',
    'ber.chipVeraltet': 'Vorlage geändert',
    'ber.treueMittel': 'Rasterfehler ⌀',
    'ber.keylineOk': 'Maß stimmt',
    'ber.spalteName': 'Icon',
    'ber.tipTreue': 'Rasterfehler: Abweichung der echten Pixel vom Ideal. 0 = perfekt, unter 0,02 sehr gut, über 0,05 auffällig.',
    'ber.tipAa': 'Weiche Pixel: Anteil halbtransparenter Randpixel. Niedriger ist schärfer, hängt von der Form ab (Kreise haben mehr).',
    'ber.tipMass': 'Maß stimmt: Das Icon füllt das vorgesehene Keyline-Maß.',
    'ber.tipSpalte': '{n} px — Rasterfehler, weiche Pixel, Maß stimmt',
    'ber.legende': 'Rasterfehler = Abweichung der echten Pixel vom Ideal (0 ist perfekt) · weiche Pixel = Anteil halbtransparenter Randpixel · Maß stimmt = Icon füllt die Keyline.',
    'ber.filter': 'Filter',
    'flt.alle': 'Alle',
    'flt.ohneSet': 'ohne Set',
    'flt.veraltet': 'Vorlage geändert',
    'flt.mass': 'Maß-Fehler',
    'flt.schlecht': 'schlechteste 10 %',
    'ber.zaehler': '{n} von {m}',
    'ber.alleSichtbaren': 'alle sichtbaren',
    'ber.keineTreffer': 'Kein Icon passt zu diesem Filter.',
    'ber.umfangAlle': 'Alle',
    'ber.umfangNamen': 'Ausgewählte ({n})',
    'ber.umfangAuswahl': 'Aktuelles Icon',
    'ber.tipUmfang': 'Ausgewählte: die angehakten Zeilen der Tabelle. Aktuelles Icon: die Auswahl im Canvas.',

    // ---- Protokoll --------------------------------------------------------
    'log.suche': 'Protokoll durchsuchen …',
    'log.allgemein': 'Allgemein',
    'log.keineTreffer': 'Nichts passt zu Filter und Suche.',
    'log.filterAlle': 'Alle',
    'log.filterFehler': 'Fehler',
    'log.filterWarn': 'Warnungen',
    'log.filterInfo': 'Hinweise',
    'log.filterOk': 'OK',
    'btn.kopieren': 'Kopieren',
    'toast.logKopiert': 'Protokoll kopiert',
    'toast.logNichts': 'Nichts zu kopieren',
    'log.groesse': '{n} px',
    'log.gruppeTip': '{err} Fehler · {warn} Warnungen · {info} Hinweise',

    // ---- Fortschritt ------------------------------------------------------
    'fort.baue': 'Baue {i}/{n}',
    'fort.rest': 'noch ca. {zeit}',
    'fort.sek': '{n} s',
    'fort.min': '{n} min'
  },
  en: {
    // ---- Preview ----------------------------------------------------------
    'diff.vergleich': 'Compare',
    'modus.ueberlagern': 'Overlay',
    'modus.wischen': 'Wipe',
    'modus.neben': 'Side by side',
    'modus.blinken': 'Blink',
    'tip.vergleich': 'Overlay: both versions on top of each other. Wipe: the handle pulls the new version over the current one. Side by side: two cells per size. Blink: swaps every 600 ms, hold space to pause.',
    'wisch.links': 'current',
    'wisch.rechts': 'new',
    'blink.hinweis': 'Hold space to pause',
    'blink.pausiert': 'paused',
    'zoom.fit': 'Fit',
    'zoom.fitTitel': 'Fit all sizes next to each other',
    'zoom.tasten': 'Keys + − 0, Ctrl+wheel zooms',
    'zelle.massOk': 'Size ok',
    'zelle.massAb': 'Size differs',
    'zelle.kontur': '{k} px stroke',
    'zelle.raster': 'Snap {r}',
    'zelle.tipVorlage': 'Source {name}',
    'px.koord': 'x {x} · y {y}',
    'px.gruppe': 'Pixel view',
    'px.differenz': 'Difference',
    'diff.nurNeu': 'new only — no existing set',

    // ---- Report -----------------------------------------------------------
    'ber.veraltet': 'source changed',
    'ber.chipVeraltet': 'source changed',
    'ber.treueMittel': 'Raster error ⌀',
    'ber.keylineOk': 'Size ok',
    'ber.spalteName': 'Icon',
    'ber.tipTreue': 'Raster error: deviation of the real pixels from the ideal. 0 = perfect, below 0.02 very good, above 0.05 noticeable.',
    'ber.tipAa': 'Soft pixels: share of semi-transparent edge pixels. Lower is sharper, depends on the shape (circles have more).',
    'ber.tipMass': 'Size ok: the icon fills the intended keyline size.',
    'ber.tipSpalte': '{n} px — raster error, soft pixels, size ok',
    'ber.legende': 'Raster error = deviation of the real pixels from the ideal (0 is perfect) · soft pixels = share of semi-transparent edge pixels · size ok = the icon fills the keyline.',
    'ber.filter': 'Filter',
    'flt.alle': 'All',
    'flt.ohneSet': 'without set',
    'flt.veraltet': 'source changed',
    'flt.mass': 'size errors',
    'flt.schlecht': 'worst 10 %',
    'ber.zaehler': '{n} of {m}',
    'ber.alleSichtbaren': 'all visible',
    'ber.keineTreffer': 'No icon matches this filter.',
    'ber.umfangAlle': 'All',
    'ber.umfangNamen': 'Selected ({n})',
    'ber.umfangAuswahl': 'Current icon',
    'ber.tipUmfang': 'Selected: the ticked rows of the table. Current icon: the canvas selection.',

    // ---- Log --------------------------------------------------------------
    'log.suche': 'Search the log …',
    'log.allgemein': 'General',
    'log.keineTreffer': 'Nothing matches filter and search.',
    'log.filterAlle': 'All',
    'log.filterFehler': 'Errors',
    'log.filterWarn': 'Warnings',
    'log.filterInfo': 'Notes',
    'log.filterOk': 'OK',
    'btn.kopieren': 'Copy',
    'toast.logKopiert': 'Log copied',
    'toast.logNichts': 'Nothing to copy',
    'log.groesse': '{n} px',
    'log.gruppeTip': '{err} errors · {warn} warnings · {info} notes',

    // ---- Progress ---------------------------------------------------------
    'fort.baue': 'Building {i}/{n}',
    'fort.rest': '~{zeit} left',
    'fort.sek': '{n} s',
    'fort.min': '{n} min'
  }
};
